name: "Notify to slack workflow"

on:
  workflow_call:
    inputs:
      #* Title of the Slack message
      title:
        required: false
        type: string
        default: "Hello QA Team :wave:, Now it's time to show your magic :magic_wand:"
      #* Footer of the Slack message
      footer:
        required: false
        type: string
        default: "Release update notify message sent by UniBot"

    #* Secrets tokens to perform the action
    secrets:
      #* Webhook URL of Slack
      slack_webhook_url:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #* Sending Slack message to channcel
      - name: Notify Slack on new release
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_USERNAME: uniBot
          SLACK_TITLE: ${{inputs.title}}
          SLACK_MESSAGE: New Release from *${{ github.event.repository.name }}* project by *${{ github.event.head_commit.committer.username }}* and release note is `${{ github.event.head_commit.message }}` is now available to test.
          SLACK_FOOTER: ${{inputs.footer}}
          MSG_MINIMAL: event,commit
          SLACK_WEBHOOK: ${{secrets.slack_webhook_url}}
