name: "Workflow"

on:
  push:
    branches:
      - main
jobs:
  run-cicd-workflow:
    uses: mohammadsaif19/uni_cicd/.github/workflows/main.yml@main
    with:
      # flutterVersion: "3.10.6"
      token: "GitHub_TOKEN"
      slack_webhook_url: "WEBHOOK_URL.com"
      slack_token: "SLACK_TOKEN"
      slack_channel_id: "SLACK_CHANNEL_ID"
